In [1]:
import torch
import numpy as np

In [2]:
dic = {"sphere":[],"cylinder":[],"cone":[]}
s1 = np.array([1,2,3],dtype = float)
s2 = np.array([9,7,5],dtype = float)
s3 = np.array([5,3,1],dtype = float)
s4 = np.array([6,1,4],dtype = float)
s5 = np.array([8,0,5],dtype = float)
s6 = np.array([2,3,5],dtype = float)
sAll = np.array([4,5,6],dtype = float)

dic["sphere"].append(np.hstack((s1,sAll)))
dic["sphere"].append(np.hstack((s2,sAll)))
dic["cylinder"].append(np.hstack((s3,sAll)))
dic["cylinder"].append(np.hstack((s4,sAll)))
dic["cone"].append(np.hstack((s5,sAll)))
dic["cone"].append(np.hstack((s6,sAll)))
print(dic)
obs_sphere,obs_cylinder,obs_cone = dic["sphere"],dic["cylinder"],dic["cone"]
print(obs_sphere)
print(obs_cylinder)
print(obs_cone)
print('*'*20)
obs_mix = obs_sphere + obs_cylinder + obs_cone
print(obs_mix)
print('%'*20)
print(obs_mix[0])

{'sphere': [array([1., 2., 3., 4., 5., 6.]), array([9., 7., 5., 4., 5., 6.])], 'cylinder': [array([5., 3., 1., 4., 5., 6.]), array([6., 1., 4., 4., 5., 6.])], 'cone': [array([8., 0., 5., 4., 5., 6.]), array([2., 3., 5., 4., 5., 6.])]}
[array([1., 2., 3., 4., 5., 6.]), array([9., 7., 5., 4., 5., 6.])]
[array([5., 3., 1., 4., 5., 6.]), array([6., 1., 4., 4., 5., 6.])]
[array([8., 0., 5., 4., 5., 6.]), array([2., 3., 5., 4., 5., 6.])]
********************
[array([1., 2., 3., 4., 5., 6.]), array([9., 7., 5., 4., 5., 6.]), array([5., 3., 1., 4., 5., 6.]), array([6., 1., 4., 4., 5., 6.]), array([8., 0., 5., 4., 5., 6.]), array([2., 3., 5., 4., 5., 6.])]
%%%%%%%%%%%%%%%%%%%%
[1. 2. 3. 4. 5. 6.]


In [3]:
obs = np.array([])

In [4]:
obs = np.hstack((obs,obs_mix[0]))
print(obs)
obs =  np.hstack((obs,obs_mix[1]))
print(obs)

[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6. 9. 7. 5. 4. 5. 6.]


In [32]:
## 拼接成一个1*n的向量
obs =  np.hstack((obs,obs_mix[2]))
print(obs)

[1. 2. 3. 4. 5. 6. 9. 7. 5. 4. 5. 6. 5. 3. 1. 4. 5. 6.]


In [33]:
noise = 0.3
noise*=0.995
noise

0.2985

In [34]:
randntest = np.random.randn(6) ## 生成1*6的服从正态分布随机数
randntest

array([ 2.61281958,  0.54516983,  0.31423286,  0.50149886, -0.46034639,
       -0.93221408])

In [35]:
np.clip(randntest,0,2)  ## 对randntest进行裁减，使其在[0,2]范围内

array([2.        , 0.54516983, 0.31423286, 0.50149886, 0.        ,
       0.        ])

In [25]:
obs_dim = 36
pi_sizes = [obs_dim] 
print(pi_sizes)
hidden_sizes = (256,256)
print(hidden_sizes)
test = list(hidden_sizes)
print(test)
print(pi_sizes+test+ [6])
print(len(pi_sizes+test+ [6]))
for i in range(4):
    print(i)
q = [[1]+[2]]
print(q)
c = torch.arange(12,dtype=torch.float32).reshape(3,4)
d = torch.tensor([[3,2.0,3,4],[1,2,3,4],[3,2,4,1]])
torch.cat((c,d),dim=0),torch.cat((c,d),dim=1),torch.cat((c,d),dim=-1)
e = torch.squeeze(d,-1)
print(e)

[36]
(256, 256)
[256, 256]
[36, 256, 256, 6]
4
0
1
2
3
[[1, 2]]
tensor([[3., 2., 3., 4.],
        [1., 2., 3., 4.],
        [3., 2., 4., 1.]])


In [23]:
x = torch.arange(12)

In [24]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [7]:
x = x.reshape(3,4)

In [8]:
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.tensor([[1,2,3,4],[3,4,2,1],[1,4,3,2]])

tensor([[1, 2, 3, 4],
        [3, 4, 2, 1],
        [1, 4, 3, 2]])

In [12]:
torch.tensor([[1,2,3,4],[3,4,2,1],[1,4,3,2]]).shape

torch.Size([3, 4])

In [13]:
a = torch.tensor([1.0,2,4,8])
b = torch.tensor([2,2,2,2])
a+b,a-b,a*b,a**b

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
##torch.cat()在给定维度上对张量序列进行连接操作
## dim=0表示竖直连接，dim=1表示水平连接
c = torch.arange(12,dtype=torch.float32).reshape(3,4)
d = torch.tensor([[3,2.0,3,4],[1,2,3,4],[3,2,4,1]])
torch.cat((c,d),dim=0),torch.cat((c,d),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 3.,  2.,  3.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 3.,  2.,  4.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  3.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  3.,  2.,  4.,  1.]]))

In [15]:
##通过逻辑运算符构建二元张量
a == b

tensor([False,  True, False, False])

In [16]:
##对张量中所有元素求和会产生只有一个元素的张量
z = torch.arange(12,dtype=torch.float32).reshape(2,6)
z.sum()

tensor(66.)

In [17]:
##可以用x[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素
c[-1]

tensor([ 8.,  9., 10., 11.])

In [18]:
c[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
## 通过指定索引将元素写入矩阵
c[1,2] = 100 ##将第1行，第二列的那个元素设置为100

In [20]:
print(c)

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9.,  10.,  11.]])


In [21]:
c[0:2,:] = 12
print(c)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [22]:
## torch.zeros_like 和c的维度一样，但是元素均为0
m = torch.zeros_like(c)
m

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
## 转换为numpy张量
NUM = c.numpy()
num = torch.tensor(NUM)
type(NUM),type(num)

(numpy.ndarray, torch.Tensor)

In [24]:
## 将大小为1的张量转换为pytho标量
n = torch.tensor([3.4])
n,n.item(),float(n),int(n)

(tensor([3.4000]), 3.4000000953674316, 3.4000000953674316, 3)

In [36]:
combined_shape_test = (10,)

In [38]:
combined_shape_test

(10,)

In [39]:
type(combined_shape_test)

tuple

In [40]:
len(combined_shape_test)

1

In [43]:
shape = np.array([1,2,3])
shape

array([1, 2, 3])

In [46]:
idxs = np.random.randint(0,128,32)
idxs

array([ 69,  51,  44,  25,  88,  78, 107,  82,  81,  32,  92,  30, 108,
        11, 113,  57,  16,  56, 103,  81,  78,  48,  12,  92,  50,  55,
        50,  57,  36,  12, 102,  42])

In [47]:
idxs2 = np.random.randint(1,2,10)

In [48]:
idxs2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [51]:
obs_buf = np.zeros((10,6),dtype=np.float32)
print(obs_buf)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [53]:
obs_buf[0] = np.array([1,2,3,4,5,6],dtype = np.float32)
obs_buf

array([[1., 2., 3., 4., 5., 6.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [56]:
idxs2 = np.random.randint(0,10,4)
idxs2

array([4, 2, 2, 3])

In [57]:
obs_buf[idxs2]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [58]:
obs2_buf = np.ones((9,8),dtype=np.float32)

In [60]:
obs2_buf[np.random.randint(0,9,3)]

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [66]:
batch = dict(OBS = obs_buf[idxs2],
            OBS2 = obs2_buf[idxs2])

In [67]:
batch

{'OBS': array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=float32),
 'OBS2': array([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)}

In [68]:
batch.items()

dict_items([('OBS', array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)), ('OBS2', array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32))])

In [71]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DICT = {k:torch.as_tensor(v,dtype=torch.float32,device = device) for k,v in batch.items()}

In [72]:
DICT

{'OBS': tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]),
 'OBS2': tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]])}

In [73]:
for _ in range(5):
    print('i love you')

i love you
i love you
i love you
i love you
i love you


In [74]:
round(2.3582,2)  ### 测试round函数的用法

2.36